# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/f11gar0/projects/orangepidriver/Call-Nurse-driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/f11gar0/projects/orangepidriver/Call-Nurse-driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f11gar0/projects/orangepidriver/Call-Nurse-driver/CMakeFiles /home/f11gar0/projects/orangepidriver/Call-Nurse-driver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f11gar0/projects/orangepidriver/Call-Nurse-driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named orangepidriver

# Build rule for target.
orangepidriver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orangepidriver
.PHONY : orangepidriver

# fast build rule for target.
orangepidriver/fast:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/build
.PHONY : orangepidriver/fast

#=============================================================================
# Target rules for targets named orangepidriver_autogen

# Build rule for target.
orangepidriver_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orangepidriver_autogen
.PHONY : orangepidriver_autogen

# fast build rule for target.
orangepidriver_autogen/fast:
	$(MAKE) -f CMakeFiles/orangepidriver_autogen.dir/build.make CMakeFiles/orangepidriver_autogen.dir/build
.PHONY : orangepidriver_autogen/fast

bytestream/ByteStream.o: bytestream/ByteStream.cpp.o

.PHONY : bytestream/ByteStream.o

# target to build an object file
bytestream/ByteStream.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/bytestream/ByteStream.cpp.o
.PHONY : bytestream/ByteStream.cpp.o

bytestream/ByteStream.i: bytestream/ByteStream.cpp.i

.PHONY : bytestream/ByteStream.i

# target to preprocess a source file
bytestream/ByteStream.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/bytestream/ByteStream.cpp.i
.PHONY : bytestream/ByteStream.cpp.i

bytestream/ByteStream.s: bytestream/ByteStream.cpp.s

.PHONY : bytestream/ByteStream.s

# target to generate assembly for a file
bytestream/ByteStream.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/bytestream/ByteStream.cpp.s
.PHONY : bytestream/ByteStream.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/main.cpp.s
.PHONY : main.cpp.s

orangepidriver_autogen/EWIEGA46WW/qrc_qml.o: orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.o

.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.o

# target to build an object file
orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.o
.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.o

orangepidriver_autogen/EWIEGA46WW/qrc_qml.i: orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.i

.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.i

# target to preprocess a source file
orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.i
.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.i

orangepidriver_autogen/EWIEGA46WW/qrc_qml.s: orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.s

.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.s

# target to generate assembly for a file
orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.s
.PHONY : orangepidriver_autogen/EWIEGA46WW/qrc_qml.cpp.s

orangepidriver_autogen/mocs_compilation.o: orangepidriver_autogen/mocs_compilation.cpp.o

.PHONY : orangepidriver_autogen/mocs_compilation.o

# target to build an object file
orangepidriver_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/mocs_compilation.cpp.o
.PHONY : orangepidriver_autogen/mocs_compilation.cpp.o

orangepidriver_autogen/mocs_compilation.i: orangepidriver_autogen/mocs_compilation.cpp.i

.PHONY : orangepidriver_autogen/mocs_compilation.i

# target to preprocess a source file
orangepidriver_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/mocs_compilation.cpp.i
.PHONY : orangepidriver_autogen/mocs_compilation.cpp.i

orangepidriver_autogen/mocs_compilation.s: orangepidriver_autogen/mocs_compilation.cpp.s

.PHONY : orangepidriver_autogen/mocs_compilation.s

# target to generate assembly for a file
orangepidriver_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/orangepidriver_autogen/mocs_compilation.cpp.s
.PHONY : orangepidriver_autogen/mocs_compilation.cpp.s

query/Query.o: query/Query.cpp.o

.PHONY : query/Query.o

# target to build an object file
query/Query.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/Query.cpp.o
.PHONY : query/Query.cpp.o

query/Query.i: query/Query.cpp.i

.PHONY : query/Query.i

# target to preprocess a source file
query/Query.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/Query.cpp.i
.PHONY : query/Query.cpp.i

query/Query.s: query/Query.cpp.s

.PHONY : query/Query.s

# target to generate assembly for a file
query/Query.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/Query.cpp.s
.PHONY : query/Query.cpp.s

query/SortedQuery.o: query/SortedQuery.cpp.o

.PHONY : query/SortedQuery.o

# target to build an object file
query/SortedQuery.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/SortedQuery.cpp.o
.PHONY : query/SortedQuery.cpp.o

query/SortedQuery.i: query/SortedQuery.cpp.i

.PHONY : query/SortedQuery.i

# target to preprocess a source file
query/SortedQuery.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/SortedQuery.cpp.i
.PHONY : query/SortedQuery.cpp.i

query/SortedQuery.s: query/SortedQuery.cpp.s

.PHONY : query/SortedQuery.s

# target to generate assembly for a file
query/SortedQuery.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/query/SortedQuery.cpp.s
.PHONY : query/SortedQuery.cpp.s

udp/UdpClient.o: udp/UdpClient.cpp.o

.PHONY : udp/UdpClient.o

# target to build an object file
udp/UdpClient.cpp.o:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/udp/UdpClient.cpp.o
.PHONY : udp/UdpClient.cpp.o

udp/UdpClient.i: udp/UdpClient.cpp.i

.PHONY : udp/UdpClient.i

# target to preprocess a source file
udp/UdpClient.cpp.i:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/udp/UdpClient.cpp.i
.PHONY : udp/UdpClient.cpp.i

udp/UdpClient.s: udp/UdpClient.cpp.s

.PHONY : udp/UdpClient.s

# target to generate assembly for a file
udp/UdpClient.cpp.s:
	$(MAKE) -f CMakeFiles/orangepidriver.dir/build.make CMakeFiles/orangepidriver.dir/udp/UdpClient.cpp.s
.PHONY : udp/UdpClient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... orangepidriver"
	@echo "... edit_cache"
	@echo "... orangepidriver_autogen"
	@echo "... bytestream/ByteStream.o"
	@echo "... bytestream/ByteStream.i"
	@echo "... bytestream/ByteStream.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... orangepidriver_autogen/EWIEGA46WW/qrc_qml.o"
	@echo "... orangepidriver_autogen/EWIEGA46WW/qrc_qml.i"
	@echo "... orangepidriver_autogen/EWIEGA46WW/qrc_qml.s"
	@echo "... orangepidriver_autogen/mocs_compilation.o"
	@echo "... orangepidriver_autogen/mocs_compilation.i"
	@echo "... orangepidriver_autogen/mocs_compilation.s"
	@echo "... query/Query.o"
	@echo "... query/Query.i"
	@echo "... query/Query.s"
	@echo "... query/SortedQuery.o"
	@echo "... query/SortedQuery.i"
	@echo "... query/SortedQuery.s"
	@echo "... udp/UdpClient.o"
	@echo "... udp/UdpClient.i"
	@echo "... udp/UdpClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

